// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multimedia_app.Models;

#nullable disable

namespace Multimedia_app.Migrations
{
    [DbContext(typeof(ArtDbContext))]
    [Migration("20260522185049_AddFileDataToArtwork")]
    partial class AddFileDataToArtwork
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Multimedia_app.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AudioFile")
                        .HasColumnType("BLOB");

                    b.Property<string>("AudioFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TextFile")
                        .HasColumnType("BLOB");

                    b.Property<string>("TextFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
